color: null
fieldLayouts:
  025aa6af-4e6e-4c52-9e69-c37947e0b3c7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-10T21:43:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ae69c686-5cf9-4068-87dd-0e2e0609e523
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00e1e72d-cd1e-4d92-9d0d-36e97aaaf393
        userCondition: null
handle: page_projects
hasTitleField: true
icon: null
name: Projects
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
