color: null
description: null
fieldLayouts:
  57080dda-6ff9-42ef-8c84-fb9f7f7a6f51:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-10T21:34:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 479c11ac-0e29-4043-909f-44d882ea6719
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-09T21:20:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f2c03b7-3707-4d1d-8eba-a28d0bb11683 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba2312e7-61b7-45df-8d86-7dcad72afa30
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 629b4395-fe0e-4641-82d5-c514f24d3695
        userCondition: null
handle: page_project
hasTitleField: true
icon: null
name: Project
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
