altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  0ae94014-3a7e-409e-95a5-501644dc6f98:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-30T20:49:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 96f64373-de8c-44ba-b6c8-47cf689d1596
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59b52925-70c1-490b-af45-4bf8e3db41f4
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
