defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f3b919f0-d800-4f6f-9e26-60a6661f0697 # Library Item
handle: library
maxAuthors: 1
name: Library
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  71b26e0c-8960-4d5b-a278-8dcac1aae074: # Nederlands
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
